server:
  port: 7016

dubbo:
  application:
    name: order-consumer-withdb
    qos-port: 88888
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    port: 20080
    name: dubbo
  monitor:
    protocol: registry